---
title: "615 sentiment analysis"
author: "Shijie Cai"
date: "2017/12/15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
library(twitteR)
library(tm)
library(stringr)
library(wordcloud)
library(SnowballC)
```

Sentiment Analysis
```{r}
library(tm)
library(syuzhet)
library(reshape2)
library(ggplot2)
```

```{r}
api_key <- 	"5TxFq8Omml0YFbOw0xtyuBv8A"
api_secret <- "MkVw0SOn9F0roAGul9RvNwl0Y4p5bDpUBhVcvUHw62giLeZXdR"
access_token <- "2240907564-2o7ZSQMMQoIAgvd46BEEzOFqbjM7R2fmc8mccyp"
access_token_secret <- "5hcnZ3pIoG0LOh0WrMtFDR09L4q8236i85m9sMIs0YSLz"
  

setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

```

```{r}

ccc<-readRDS("ccc.rds")
mmm<-readRDS("mmm.rds")
players<-list(CristianoRonaldo=ccc, LeoMessi=mmm)

## CLeaning
clean.text <- function(some_txt){
  some_txt = gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", some_txt)
  some_txt = gsub("@\\w+", "", some_txt)
  some_txt = gsub("[[:punct:]]", "", some_txt)
  some_txt = gsub("[[:digit:]]", "", some_txt)
  some_txt = gsub("http\\w+", "", some_txt)
  some_txt = gsub("[ \t]{2,}", "", some_txt)
  some_txt = gsub("^\\s+|\\s+$", "", some_txt)
  some_txt = gsub("amp", "", some_txt)
  # define "tolower error handling" function
  try.tolower = function(x)
  {
    y = NA
    try_error = tryCatch(tolower(x), error=function(e) e)
    if (!inherits(try_error, "error"))
      y = tolower(x)
    return(y)
  }
  some_txt = sapply(some_txt, try.tolower)
  names(some_txt) = NULL
  return(some_txt)
}

player.text <- lapply(players, FUN=function(x) {clean.text(x$text)})
player.sentiment <- lapply(player.text, FUN=function(x) {get_nrc_sentiment(x)})
saveRDS(player.sentiment, file='player.sentiment.rds')
```

Sentiment analysis for players Leo Messi and Cristiano Ronaldo

```{r}
m.sentiment<-player.sentiment$LeoMessi
messi<-melt(m.sentiment, measure.vars  = c("anger", "anticipation","disgust", "fear","joy", "sadness","surprise","trust","negative","positive"))
saveRDS(messi, file='messi.sentiment.rds')


c.sentiment<-player.sentiment$CristianoRonaldo
cris<-melt(c.sentiment, measure.vars  = c("anger", "anticipation","disgust", "fear","joy", "sadness","surprise","trust","negative","positive"))
saveRDS(cris, file='cristiano.sentiment.rds')

bm<-ggplot(messi, aes(variable,value))
bm<-bm +geom_bar(stat = "identity")+coord_flip()
bm<-bm + ggtitle("Sentiment Analysis for Messi")
bm

cm<-ggplot(cris, aes(variable,value))
cm<-cm +geom_bar(stat = "identity")+coord_flip()
cm<- cm + ggtitle("Sentiment Analysis for Cristiano")
cm
```

Messi has 868 observations but Cristiano has only 167 observations. However, there is no disgust word for Cristiano and proportion of negative word is smaller. It seems that people has more anticipation for Messi compare to Cristiano.

